services:
  metaexchange.webservice:
    image: metaexchange.webservice
    ports:
      - "5075:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RootFolderPathOfExchanges=/exchanges
    volumes:
      - ./ExampleData/exchanges:/exchanges:ro